/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Prod model module.
 * @module model/Prod
 * @version 1.0.0
 */
class Prod {
    /**
     * Constructs a new <code>Prod</code>.
     * @alias module:model/Prod
     * @param text {String} 
     */
    constructor(text) { 
        
        Prod.initialize(this, text);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, text) { 
        obj['text'] = text;
    }

    /**
     * Constructs a <code>Prod</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Prod} obj Optional instance to populate.
     * @return {module:model/Prod} The populated <code>Prod</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Prod();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Prod.prototype['_id'] = undefined;

/**
 * @member {String} text
 */
Prod.prototype['text'] = undefined;






export default Prod;

